/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    `application`
    id("org.openjfx.javafxplugin").version("0.1.0")
}

repositories {
    mavenCentral()
    mavenLocal()
    maven {
        url = uri("https://repository.sonatype.org/content/groups/public/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    compileOnly(libs.org.jetbrains.annotations)
    compileOnly("org.apache.maven.plugins:maven-assembly-plugin:3.7.1")
    testImplementation(libs.org.junit.vintage.junit.vintage.engine)
    // --- BEGINNING OF NON MODULE DEPENDENCIES ---
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.10.1")
    implementation("commons-io:commons-io:2.14.0")
    implementation("org.imgscalr:imgscalr-lib:4.2")
    implementation("com.jgoodies:jgoodies-forms:1.9.0")
    implementation("com.cedarsoftware:json-io:4.14.1")
    implementation("com.thoughtworks.xstream:xstream:1.4.21")
    implementation("commons-cli:commons-cli:1.9.0")
    // --- END OF NON MODULE DEPENDENCIES --
    implementation(libs.org.apache.commons.commons.lang3)
    implementation(libs.commons.codec.commons.codec)
    implementation(libs.org.apache.commons.commons.csv)
    implementation(libs.com.jgoodies.jgoodies.common)
    implementation(libs.org.hamcrest.hamcrest.core)
    implementation(libs.org.json.json)
    implementation(libs.io.jsondb.jsondb.core)
    implementation(libs.org.jsoup.jsoup)
    implementation(libs.org.apache.httpcomponents.httpcore)
    implementation(libs.org.apache.httpcomponents.httpclient)
    implementation(libs.com.github.ben.manes.caffeine.caffeine)
    implementation(libs.com.twelvemonkeys.imageio.imageio.webp)
}

group = "com.github.youngerdryas89.moviescraper"
version = "0.9.5"
description = "JAVMovieScraper"
java.sourceCompatibility = JavaVersion.VERSION_21
java.modularity.inferModulePath = true

javafx {
    version = "24.0.1"
    modules = mutableListOf("javafx.controls", "javafx.graphics", "javafx.swing")
}

application {
    mainModule = "com.github.youngerdryas89.moviescraper"
    mainClass = "com.github.youngerdryas89.moviescraper.Main"
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
