/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.github.youngerdryas89.moviescraper.view.scrapersettings;

import com.github.youngerdryas89.moviescraper.view.scrapersettings.ScraperSettingsModel;
import com.github.youngerdryas89.moviescraper.view.renderer.ScraperRenderer;
import java.awt.SystemColor;
import static javax.swing.JSplitPane.HORIZONTAL_SPLIT;
import javax.swing.UIManager;

/**
 *
 * @author sai
 */
public class ScraperSettingsGUI_ extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ScraperSettingsGUI_.class.getName());

    /**
     * Creates new form ScraperSettingsGUI
     */
    public ScraperSettingsGUI_() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ScraperListerPanel = new javax.swing.JPanel();
        ScraperListerScrollPanel = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        SettingsPanel = new javax.swing.JPanel();
        SettingsScrollPanel = new javax.swing.JScrollPane();
        jSplitPane1 = new javax.swing.JSplitPane(HORIZONTAL_SPLIT, ScraperListerPanel, SettingsPanel);

        ScraperListerPanel.setLayout(new javax.swing.BoxLayout(ScraperListerPanel, javax.swing.BoxLayout.LINE_AXIS));

        ScraperListerScrollPanel.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jList1.setModel(new ScraperSettingsModel());
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setCellRenderer(new ScraperRenderer());
        ScraperListerScrollPanel.setViewportView(jList1);

        ScraperListerPanel.add(ScraperListerScrollPanel);

        SettingsPanel.setLayout(new java.awt.BorderLayout());
        SettingsPanel.add(SettingsScrollPanel, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Settings");
        setBackground(SystemColor.window);
        setMinimumSize(new java.awt.Dimension(900, 450));

        jSplitPane1.setBackground(SystemColor.window);
        jSplitPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jSplitPane1.setDividerSize(7);
        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
//Prevent text area font from looking different than text field font
            UIManager.getDefaults().put("TextArea.font", UIManager.getFont("TextField.font"));
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ScraperSettingsGUI_().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ScraperListerPanel;
    private javax.swing.JScrollPane ScraperListerScrollPanel;
    private javax.swing.JPanel SettingsPanel;
    private javax.swing.JScrollPane SettingsScrollPanel;
    private javax.swing.JList<String> jList1;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
