module com.github.youngerdryas89 {
    requires javafx.swing;
    requires javafx.controls;
    requires commons.cli;
    requires org.apache.commons.io;
    requires java.desktop;
    requires org.apache.commons.lang3;
    requires org.jsoup;
    requires imgscalr.lib;
    requires json.io;
    requires jgoodies.forms;
    requires org.apache.httpcomponents.httpcore;
    requires org.apache.httpcomponents.httpclient;
    requires org.apache.commons.csv;
    requires org.json;
    requires java.logging;
    requires org.apache.commons.codec;
    requires xstream;
    requires java.sql;
    requires org.junit.jupiter.api;
    requires annotations;
    requires org.jetbrains.annotations;
    requires commons.collections;
    requires JImageHash;
    requires commons.math3;
    requires com.github.benmanes.caffeine;
    exports com.github.youngerdryas89;
    exports com.github.youngerdryas89.controller.amalgamation;
    exports com.github.youngerdryas89.controller.siteparsingprofile;
    exports com.github.youngerdryas89.controller.siteparsingprofile.specific;
    exports com.github.youngerdryas89.model.dataitem;
    opens com.github.youngerdryas89.controller.amalgamation to json.io, xstream;
    opens com.github.youngerdryas89.controller.siteparsingprofile to xstream;
    opens com.github.youngerdryas89.controller.siteparsingprofile.specific to xstream;
    opens com.github.youngerdryas89.model.preferences to xstream;
    opens com.github.youngerdryas89.model.dataitem to xstream;
    opens com.github.youngerdryas89.controller.xmlserialization to xstream;
}
