module moviescraper.doctord {
    requires javafx.swing;
    requires javafx.controls;
    requires commons.cli;
    requires org.apache.commons.io;
    requires java.desktop;
    requires org.apache.commons.lang3;
    requires org.jsoup;
    requires imgscalr.lib;
    requires json.io;
    requires jgoodies.forms;
    requires org.apache.httpcomponents.httpcore;
    requires org.apache.httpcomponents.httpclient;
    requires org.apache.commons.csv;
    requires org.json;
    requires java.logging;
    requires org.apache.commons.codec;
    requires xstream;
    requires java.sql;
    requires org.junit.jupiter.api;
    requires annotations;
    requires org.jetbrains.annotations;
    requires commons.collections;
    requires com.github.benmanes.caffeine;
    requires com.fasterxml.jackson.databind;
    requires com.fasterxml.jackson.annotation;
    requires com.fasterxml.jackson.core;
    exports com.github.youngerdryas89.moviescraper;
    exports com.github.youngerdryas89.moviescraper.controller.amalgamation;
    exports com.github.youngerdryas89.moviescraper.controller.siteparsingprofile;
    exports com.github.youngerdryas89.moviescraper.controller.siteparsingprofile.specific;
    exports com.github.youngerdryas89.moviescraper.model.dataitem;
    opens com.github.youngerdryas89.moviescraper.controller.amalgamation to json.io, xstream;
    opens com.github.youngerdryas89.moviescraper.controller.siteparsingprofile to xstream;
    opens com.github.youngerdryas89.moviescraper.controller.siteparsingprofile.specific to xstream;
    opens com.github.youngerdryas89.moviescraper.model.preferences to xstream;
    opens com.github.youngerdryas89.moviescraper.model.dataitem to xstream;
    opens com.github.youngerdryas89.moviescraper.controller.xmlserialization to xstream;
}
